Fix exception does not have message object
❯❯❯ python ./emptyVersionedBucket.py -p myprofile -d -b mybucket
Traceback (most recent call last):
  File "./emptyVersionedBucket.py", line 42, in <module>
    run()
  File "./emptyVersionedBucket.py", line 19, in run
    bucket.object_versions.delete()
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/boto3/resources/collection.py", line 515, in batch_action
    return action(self, *args, **kwargs)
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/boto3/resources/action.py", line 128, in __call__
    for page in parent.pages():
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/boto3/resources/collection.py", line 166, in pages
    for page in pages:
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the ListObjectVersions operation: The specified bucket does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./emptyVersionedBucket.py", line 44, in <module>
    print(e.message)
AttributeError: 'NoSuchBucket' object has no attribute 'Message'